### PR TITLE
[BUG] Fix animated marker not pausing with game

### LINKED ISSUE #21: Pause doesn't stop the marker animation
https://github.com/kckaiwei/TurnMarker-alt/blob/fd45f2db85c3a4b8b9f2254780194047ba4f0687/src/scripts/turnmarker.js#L60-L64

`placeTurnMarker` returns only the marker id. The code above sets `markerId` and `animator` to `undefined`. Therefore pause/unpause doesn't stop/start the spinning animation.

I also noticed that `!game.paused && ` is missing here:

https://github.com/kckaiwei/TurnMarker-alt/blob/fd45f2db85c3a4b8b9f2254780194047ba4f0687/src/scripts/turnmarker.js#L41

EDIT: And the `pauseGame` hook doesn't need to be `async`.

### PR DESCRIPTION
**Pull request by dev7355608**
The globals `markerId` and `animator` are unnecessary, and getting rid of them fixed most of the problems already.

### CODE REVIEW

File: src/scripts/turnmarker.js [hunk 1]
```diff
@@ -5,44 +5,44 @@ import { Settings } from './settings.js';
...
 import { firstGM, Flags, FlagScope, socketAction, socketName } from './utils.js';
 
-let animator;
-let markerId;
+
 let lastTurn = '';
 
 
-Hooks.on('ready', async () => {
+Hooks.once('init', () => {
```
Comment (kckaiwei) [inline src/scripts/turnmarker.js:12]: What's the difference between 'ready' and 'init'. There's not really much docs on the hooks, and I'm still new to this.

I'm assuming 'init' is fired on initialization of everything, and ready is fired when the scene/map/browser is ready to render?

**Review by kckaiwei — APPROVED** [review]
Looks good to me, and testing works as intended.

File: src/scripts/turnmarker.js (hunk 1 above)
Comment (dev7355608) [reply src/scripts/turnmarker.js:11]: This more or less like this:

1. `"init"` is called directly after `game` was created. This the earliest hook.
2. Then comes `"setup"` directly before `game` is setup (entities, UI, canvas, ...)
4. Then `"canvasInit"` after the canvas is created.
5. Then `"canvasReady"` after the canvas and its layers are drawn.
6. And finally `"ready"` when everything else is ready as well (keyboard, sockets, ...).

All these hooks are called once except `"canvasInit"`/`"canvasReady"`, which are also called every time the scene is switched.

For more details look at the `DOMContentLoaded` listener, and follow the code from there.
